spring.application.name=UniCycle Backend
# Use 'db' (the service name) instead of 'localhost'
spring.datasource.url=jdbc:postgresql://db:5432/unicycle_db
spring.datasource.username=user
spring.datasource.password=pass


# This tells Hibernate to create the tables for you automatically
spring.jpa.hibernate.ddl-auto=update