spring.application.name=UniCycle Backend

# Use environment variables with local fallbacks
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/unicycle_db}
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:pass}

# JWT Secret (No fallback here for security)
jwt.secret=${JWT_SECRET}

# Keep this for local dev, but you'll change it in prod
spring.jpa.hibernate.ddl-auto=update